# Generated by Django 5.2.1 on 2025-09-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposite_date',
            new_name='initial_deposit_date',
        ),
    ]
